CREATE TABLE ROLES (
    ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255)
) ENGINE=INNODB;

CREATE TABLE PERMISSIONS (
    PERMISSION_ID INT AUTO_INCREMENT PRIMARY KEY,
    PERMISSION_NAME VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255)
) ENGINE=INNODB;

CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(PERMISSION_ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,  
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(200) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    BIRTHDAY DATE NOT NULL,
    AGE INT GENERATED ALWAYS AS (TIMESTAMPDIFF(YEAR, BIRTHDAY, CURDATE())) VIRTUAL,
    ACCOUNT_STATUS ENUM('A', 'I') NOT NULL DEFAULT 'A',
    CIVIL_STATUS ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED') NOT NULL,
    CREATEDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME NULL
) ENGINE=INNODB;

CREATE TABLE USER_ROLES (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE USERS_OTP (
    OTP_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    OTP VARCHAR(8) NOT NULL,
    STATUS CHAR(1) NOT NULL DEFAULT 'A' CHECK (STATUS IN ('A', 'E', 'U')),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_DATE DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=INNODB;

CREATE TABLE USER_ADDRESSES (
    ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL UNIQUE,
    STREET NVARCHAR(200) NOT NULL,
    CITY NVARCHAR(100) NOT NULL,
    STATE NVARCHAR(100) NOT NULL,
    ZIPCODE NVARCHAR(20) NOT NULL,
    COUNTRY NVARCHAR(100) NOT NULL,
    CREATEDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=INNODB;

CREATE TABLE FAILED_LOGINS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ATTEMPTDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=INNODB;

CREATE TABLE SESSIONS (
    SESSION_ID VARCHAR(16) PRIMARY KEY,
    USER_ID INT NOT NULL,
    JWT VARCHAR(512) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE INDEX idx_user_id_otp ON USERS_OTP(USER_ID);
CREATE INDEX idx_user_id_addresses ON USER_ADDRESSES(USER_ID);
CREATE INDEX idx_user_id_failed_logins ON FAILED_LOGINS(USER_ID);
CREATE INDEX idx_session_id ON SESSIONS(SESSION_ID);